version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-tg_cosmetics}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://localhost:27017/${MONGO_DB_NAME:-tg_cosmetics}",
          "--eval",
          "db.runCommand({ ping: 1 })"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:
